/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#3e494a",
        "inverse-primary": "#82d3de",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ffb783",
        "primary": "#00535b",
        "error": "#ba1a1a",
        "background": "#f8f9fa",
        "on-primary-fixed": "#001f23",
        "on-error-container": "#93000a",
        "outline-variant": "#bec8ca",
        "primary-fixed": "#9ff0fb",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "secondary-container": "#dde0e5",
        "on-error": "#ffffff",
        "tertiary-container": "#8e5426",
        "error-container": "#ffdad6",
        "secondary": "#5b5f63",
        "on-secondary-container": "#5f6368",
        "on-secondary-fixed": "#181c20",
        "primary-container": "#006d77",
        "surface-container-high": "#e7e8e9",
        "on-tertiary-container": "#ffd7bd",
        "surface-bright": "#f8f9fa",
        "on-background": "#191c1d",
        "surface-container-highest": "#e1e3e4",
        "on-surface": "#191c1d",
        "surface-container": "#edeeef",
        "tertiary-fixed": "#ffdcc5",
        "primary-fixed-dim": "#82d3de",
        "secondary-fixed": "#e0e3e8",
        "on-tertiary-fixed": "#301400",
        "on-primary-fixed-variant": "#004f56",
        "inverse-surface": "#2e3132",
        "surface-container-low": "#f3f4f5",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#c3c7cc",
        "outline": "#6f797a",
        "on-primary-container": "#9becf7",
        "tertiary": "#713d10",
        "surface-variant": "#e1e3e4",
        "surface-dim": "#d9dadb",
        "inverse-on-surface": "#f0f1f2",
        "on-secondary-fixed-variant": "#43474c",
        "surface-tint": "#006972",
        "surface": "#f8f9fa",
        "on-tertiary-fixed-variant": "#6d390c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "touch-target-min": "44px",
        "stack-md": "16px",
        "margin-desktop": "24px",
        "stack-sm": "8px",
        "gutter": "12px"
      },
      fontFamily: {
        "headline-lg": ["Outfit", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-sm": ["Outfit", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "display-lg": ["Outfit", "sans-serif"],
        "data-mono": ["Inter", "monospace"]
      }
    },
  },
  plugins: [],
}
